[package]
name = "egui-data-table"
version = "0.4.0"
edition = "2021"
authors = ["kang-sw"]
description = "A generic data table widget implementation for egui (fork)"
readme = "README.md"
categories = ["gui"]
license-file = "LICENSE"

[lib]
name = "egui_data_table"
path = "src/lib.rs"

[[example]]
name = "demo"
path = "examples/demo.rs"

[dependencies]
egui = "0.33"
egui_extras = { version = "0.33", default-features = false, features = ["serde"] }
tap = "1"
itertools = "0.13"
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = "2"

[dev-dependencies]
eframe = { version = "0.33", features = ["serde", "persistence"] }
fastrand = "2"
names = { version = "0.14", default-features = false }

[features]
default = ["persistency"]
persistency = ["dep:serde"]
