# Generated by Django 2.2.7 on 2019-11-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('batch_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanbanbomsapp.BOM')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanbanbomsapp.Request')),
            ],
        ),
        migrations.CreateModel(
            name='BOMEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanbanbomsapp.BOM')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='kanbanbomsapp.BOM')),
            ],
        ),
    ]
