# Generated by Django 2.2.7 on 2019-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanbomsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomentry',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
