# Generated by Django 2.2.7 on 2019-11-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanbomsapp', '0002_bomentry_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomentry',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
