# Generated by Django 3.0.6 on 2020-05-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanbomsapp', '0003_auto_20191116_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='location',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
